services:
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - '81:80'
        depends_on:
            - backend
        networks:
            - app-network

    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        environment:
            - PORT=3001
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
