name: CD

run: |
    echo "HOST=[${{ secrets.HOST }}]"
    echo "USER=[${{ secrets.USER }}]"

on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: SSH & deploy
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      set -e
                      cd /root/game-wander
                      git pull origin main
                      docker-compose up -d --build
